server:
  port: 9090

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/AuthDB
    username: postgres
    password: 123456789
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

my-project:
  user-service:
    ip: localhost
    port: 9092
    ur: "http://localhosty:9092/api/v1/user"