server:
  servlet:
      session:
        timeout: 120
  port: 9092

spring:
  security:
    user:
      name: yasin
      password: 12345
  rabbitmq:
    host:
    port: 5672
    username: admin
    password: root
  cloud:
    compatibility-verifier:
      enabled: false
  zipkin:
    enabled: false
    base-url: http://localhost:9411
    service:
      name: user-server
  data:
    mongodb:
      host: localhost
      port: 27017
      database: sosyalmedyadb
      username: admin
      password: root

# myapplication:
    #   redis:
    #    host: ${REDIS_HOST}
  #    port: ${REDIS_PORT}