apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-pod-label-user
  template:
    metadata:
      labels:
       app: deployment-pod-label-user
    spec:       
      containers: 
      - name: user
        image: ysnslk/java8userservice:v02
        resources:
          requests: 
            cpu: "300m"
            memory: "1024Mi"
          limits:
            cpu: "500m"
            memory: "2048Mi"  
        ports: 
        - containerPort: 9092
        env:
          - name: CONFIG_SERVER_URL
            value: http://10.56.13.13:8888
            
