apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-pod-label-rabbitmq
  template:
    metadata:
      labels:
       app: deployment-pod-label-rabbitmq
    spec:       
      containers: 
      - name: rabbitmq
        image: rabbitmq:3-management
        resources:
          requests: 
            cpu: "300m"
            memory: "1024Mi"
          limits:
            cpu: "500m"
            memory: "2048Mi"  
        ports: 
        - containerPort: 5672
        - containerPort: 15672
        env:
          - name: RABBITMQ_DEFAULT_USER
            value: bilgejava8
          - name: RABBITMQ_DEFAULT_PASS
            value: bilgeadmin*
