apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-mongo-export-ip
spec:
  selector:
    app: deployment-pod-label-mongodb 
  type: ClusterIP
  ports:
    - name: mongoport
      port: 27017
      targetPort: 27017
