apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-rabbitmq-export-ip
spec:
  selector:
    app: deployment-pod-label-rabbitmq 
  type: ClusterIP
  ports:
    - name: rabbitmqport
      port: 5672
      targetPort: 5672
