apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-config-export-ip
spec:
  selector:
    app: deployment-pod-label-config 
  type: ClusterIP
  ports:
    - name: configport
      port: 8888
      targetPort: 8888
