apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-postgre-export-ip
spec:  
  # Servis objeleri, bir network ağ yapısı şeklindedirler. Bu yüzden kendilerinden
  # bağlanacak bileşenlere ağ trafiğini yönlendirirler. Bu nedenle podların
  # otomatik olarak bu ağa bağlanmasını sağlamak için selector ile label ları 
  # tanımlamak gereklidir.
  selector:
    app: deployment-pod-label-postgresql
  # Servis objeleri 3 şekilde tanımlanır ve kullanılır.
  # NodePortÇ nodlar arası erişimi açmak için
  # ClusterIP: aynı node içinde podların sabit bir network üzerinden haberleşmesi için 
  # LoadBalancer: İç ağı dışarıya internet açmak için kullanılır.  
  type: ClusterIP
  # Podların iletişime açılacağı portları ve dış dünyaya açılmak istenilen
  # portları belirliyoruz.
  ports:
    - name: postgreport
      port: 5432
      targetPort: 5432
